image:
  file: .gitpod.Dockerfile
  context: mycontext

ports:
  - port: 8001
    onOpen: open-preview
  - port: 9003
    onOpen: ignore
  - port: 9004
    onOpen: ignore
  - port: 3306
    onOpen: ignore

tasks:
- name: Terminal
  command: >
    echo "";
    echo "Commands you can try:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
